[package]
name = "box"
version = "0.1.0"
authors = ["oct16 <mail@fengfan.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
